openapi: 3.0.3
info:
  title: Schema dell' Esito del Pagamento
  version: 202301.10.00
  x-summary: Schema dell'Esito di un Pagamento compatibile con l'Ontologia INPS relativa a Riscatti, Ricongiunzioni, Rendite e Lavoratore Domestico.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Eugenia Alessio
    email: e.alessio@almawave.it
  description: |-
   Esprime l'esito dell'unico pagamento a cui è associato.
   L'esito di un pagamento può non essere immediatamente noto poichè l'esecuzione del pagamento può coinvolgere diversi intermediari che potrebbero non comunicare in tempo reale l'effettivo buon fine dell'operazione a loro carico.
   La metadatazione semantica degli schemi si basa sul documento [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
   che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:

    IdEsitoPagamento:
      type: string
      description:
        Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
        Associato a https://w3id.org/italia/onto/OP21/identificatoreEsitoPagamento.
      example: '12345'
      maxLength: 50
      minLength: 1

    EsitoPagamento:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/OP21/EsitoPagamento
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/OP21/"
        codice_esito_pagamento: identificatoreEsitoPagamento
        descrizione_esito_pagamento: descrizioneEsitoPagamento
        riferisce_pagamento:
          "@id": riferiscePagamento
      additionalProperties: true
      description:
          Questo schema rappresenta l'Esito di un pagamento ed è associato a https://w3id.org/italia/onto/OP21/EsitoPagamento.
      required:
      - codice_esito_pagamento
      - descrizione_esito_pagamento
      properties:
        codice_esito_pagamento:
          $ref: "#/components/schemas/IdEsitoPagamento"
        descrizione_esito_pagamento:
          type: string
          maxLength: 250
        riferisce_pagamento:
          type: object
          items:
            $ref: "#/components/schemas/Pagamento"
      example:
        codice_esito_pagamento: '12345'
        descrizione_esito_pagamento: 'Positivo'
        riferisce_pagamento:
          importo_pagamento: 500.50
          data_pagamento: '2022-06-25'
          ha_notifica_pagamento:
            codice_mav: 01234567890123456
          attiva_ordine_pagamento:
            codice_ordine_pagamento: '987654321'
            data_ordine_pagamento: '2022-06-30'
            utilizza_servizio_pagamento:
              id_servizio_pagamento: '16986'
            esegue_accredito:
              id_movimento: '154864'
              causale_movimento: 'Pagamento'
              importo_movimento: 500.50
              importo_commissione_movimento: 2.50
              data_movimento: '2022-07-14'
              invia_ricevuta_movimento:
                id_ricevuta_accredito: '123546'
                data_ricevuta: '2022-07-25'
            esegue_addebito:
              id_movimento: '54864'
              causale_movimento: 'Pagamento'
              importo_movimento: 500.50
              importo_commissione_movimento: 2.50
              data_movimento: '2022-07-14'
              invia_ricevuta_movimento:
                id_ricevuta_accredito: '123546'
                data_ricevuta: '2022-07-25'

    Pagamento:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/OP21/Pagamento
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/OP21/"
        importo_pagamento: importoPagamento
        data_pagamento: dataPagamento
        ha_notifica_pagamento:
          "@id": haNotificaDiPagamento
        attiva_ordine_pagamento:
          "@id": attivaOrdineDiPagamento
      additionalProperties: true
      description:
         Questo schema rappresenta un pagamento, ovvero il trasferimento di una somma di denaro come corrispettivo di una prestazione o come mezzo di estinzione di un'obbligazione.
         Lo schema è associato a https://w3id.org/italia/onto/OP21/Pagamento.
      required:
      - importo_pagamento
      - data_pagamento
      properties:
        importo_pagamento:
          type: number
          format: double
        data_pagamento:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        ha_notifica_pagamento:
          type: object
          items:
            $ref: "#/components/schemas/BollettinoMav"
        attiva_ordine_pagamento:
          type: object
          items:
            $ref: "#/components/schemas/OrdinePagamento"
      example:
        importo_pagamento: 500.50
        data_pagamento: '2022-06-25'
        ha_notifica_pagamento:
          codice_mav: 01234567890123456
        attiva_ordine_pagamento:
          codice_ordine_pagamento: '987654321'
          data_ordine_pagamento: '2022-06-30'
          utilizza_servizio_pagamento:
            id_servizio_pagamento: '16986'
          esegue_accredito:
            id_movimento: '154864'
            causale_movimento: 'Pagamento'
            importo_movimento: 500.50
            importo_commissione_movimento: 2.50
            data_movimento: '2022-07-14'
            invia_ricevuta_movimento:
              id_ricevuta_accredito: '123546'
              data_ricevuta: '2022-07-25'
          esegue_addebito:
            id_movimento: '54864'
            causale_movimento: 'Pagamento'
            importo_movimento: 500.50
            importo_commissione_movimento: 2.50
            data_movimento: '2022-07-14'
            invia_ricevuta_movimento:
              id_ricevuta_accredito: '123546'
              data_ricevuta: '2022-07-25'

    BollettinoMav:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/OP21/BollettinoMAV
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/OP21/"
        codice_mav: codiceMAV
      additionalProperties: true
      description:
          Questo schema rappresenta il bollettino MAV (Pagamento Mediante Avviso), ovvero un bollettino il cui pagamento segue una procedura interbancaria standard e che contiene le informazioni necessarie alla banca del creditore e al creditore stesso per la riconciliazione del pagamento.
          Lo schema è associato a https://w3id.org/italia/onto/OP21/BollettinoMAV.
      required:
      - codice_mav
      properties:
        codice_mav:
          type: integer
          format: int64
      example:
        codice_mav: 01234567890123456

    OrdinePagamento:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/OP21/OrdineDiPagamento
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/OP21/"
        codice_ordine_pagamento: identificatoreOrdinePagamento
        data_ordine_pagamento: dataOrdinePagamento
        utilizza_servizio_pagamento:
          "@id": utilizzaServizioDiPagamento
        esegue_accredito:
          "@id": esegueAccredito
        esegue_addebito:
          "@id": esegueAddebito
      additionalProperties: true
      description:
          Questo schema rappresenta l'Ordine di un Pagamento, ovvero la materializzazione di un Pagamento eseguito tramite un Servizio Di Pagamento erogato da un PSP (Prestatore Servizi Pagamento).
          Lo schema è associato a https://w3id.org/italia/onto/OP21/OrdineDiPagamento.
      required:
      - codice_ordine_pagamento
      - data_ordine_pagamento
      properties:
        codice_ordine_pagamento:
          type: string
          maxLength: 50
        data_ordine_pagamento:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        utilizza_servizio_pagamento:
          type: object
          items:
            $ref: "#/components/schemas/ServizioPagamento"
        esegue_accredito:
          type: object
          items:
            $ref: "#/components/schemas/MovimentoDiDenaro"
        esegue_addebito:
          type: object
          items:
            $ref: "#/components/schemas/MovimentoDiDenaro"
      example:
        codice_ordine_pagamento: '987654321'
        data_ordine_pagamento: '2022-06-30'
        utilizza_servizio_pagamento:
          id_servizio_pagamento: '16986'
        esegue_accredito:
          id_movimento: '154864'
          causale_movimento: 'Pagamento'
          importo_movimento: 500.50
          importo_commissione_movimento: 2.50
          data_movimento: '2022-07-14'
          invia_ricevuta_movimento:
            id_ricevuta_accredito: '123546'
            data_ricevuta: '2022-07-25'
        esegue_addebito:
          id_movimento: '54864'
          causale_movimento: 'Pagamento'
          importo_movimento: 500.50
          importo_commissione_movimento: 2.50
          data_movimento: '2022-07-14'
          invia_ricevuta_movimento:
            id_ricevuta_accredito: '123546'
            data_ricevuta: '2022-07-25'

    ServizioPagamento:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/OP21/ServizioDiPagamento
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/OP21/"
        id_servizio_pagamento: codiceServizioDiPagamento
      additionalProperties: true
      description:
          Questo schema rappresenta Servizio di pagamento offerto da un Prestatore Di Servizi Di Pagamento (PSP).
          Lo schema è associato a https://w3id.org/italia/onto/OP21/ServizioDiPagamento.
      required:
      - id_servizio_pagamento
      properties:
        id_servizio_pagamento:
          type: string
          maxLength: 50
      example:
        id_servizio_pagamento: '16986'

    MovimentoDiDenaro:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/OP21/MovimentoDiDenaro
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/OP21/"
        id_movimento: identificatoreMovimento
        causale_movimento: causaleMovimento
        importo_movimento: importoMovimento
        importo_commissione_movimento: importoCommissioneMovimento
        data_movimento: dataMovimento
        invia_ricevuta_movimento:
          "@id": inviaRicevutaDiMovimento
      additionalProperties: true
      description:
          Questo schema rappresenta il movimento di una somma di denaro indotto da un Ordine Di Pagamento su un Conto Corrente.
          Tale movimento aumenta (accredito) o diminuisce (addebito) la disponibilità di denaro del Conto Corrente. Può essere addebita una commissione per l'esecuzione del movimento, solitamente nell'operazione di addebito.
          Lo schema è associato a https://w3id.org/italia/onto/OP21/MovimentoDiDenaro.
      required:
      - id_movimento
      - causale_movimento
      - importo_movimento
      - importo_commissione_movimento
      - data_movimento
      properties:
        id_movimento:
          type: string
          maxLength: 50
        causale_movimento:
          type: string
          maxLength: 255
        importo_movimento:
          type: number
          format: double
        importo_commissione_movimento:
          type: number
          format: double
        data_movimento:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        invia_ricevuta_movimento:
          type: object
          items:
            $ref: "#/components/schemas/RicevutaDiMovimento"
      example:
        id_movimento: '154864'
        causale_movimento: 'Pagamento'
        importo_movimento: 500.50
        importo_commissione_movimento: 2.50
        data_movimento: '2022-07-14'
        invia_ricevuta_movimento:
          id_ricevuta_accredito: '123546'
          data_ricevuta: '2022-07-25'

    RicevutaDiMovimento:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/OP21/RicevutaDiMovimento
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/OP21/"
        id_ricevuta_accredito: identificatoreRicevuta
        data_ricevuta: dataRicevuta
      additionalProperties: true
      description:
          Attestazione rivolta all'Ente Creditore dell'avvenuto movimento di accredito di una somma di denaro determinata da un Movimento Di Denaro indotto da un Ordine Di Pagamento.
          Lo schema è associato a https://w3id.org/italia/onto/OP21/RicevutaDiMovimento.
      required:
      - id_ricevuta_accredito
      - data_ricevuta
      properties:
        id_ricevuta_accredito:
          type: string
          maxLength: 50
        data_ricevuta:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
      example:
        id_ricevuta_accredito: '123546'
        data_ricevuta: '2022-07-25'
